/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author parks
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    
    private List<Integer> numerosCarregados = new ArrayList<>();
    
    public String chamarSelecionados(){
        List<String> metodosSelecionados = new ArrayList();
        
        if (chbBolha.isSelected()){
            metodosSelecionados.add("Bolha");
        }
        if (chbSelecao.isSelected()){
            metodosSelecionados.add("Seleção");
        }
        if (chbPente.isSelected()){
            metodosSelecionados.add("Pente");
        }
        if (chbInsercao.isSelected()){
            metodosSelecionados.add("Inserção");
        }
        if (chbAgitacao.isSelected()){
            metodosSelecionados.add("Agitação");
        }
        
        return metodosSelecionados.toString();
    }
    
    private void carregarArquivo() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();
            List<Integer> numeros = lerArquivo(arquivo);

            // Executar métodos de ordenação
            List<Resultado> resultados = new ArrayList<>();

            resultados.add(Metodos.bolha(numeros));
            resultados.add(Metodos.selecao(numeros));
            resultados.add(Metodos.insercao(numeros));
            resultados.add(Metodos.agitacao(numeros));
            resultados.add(Metodos.pente(numeros));

            // Mostrar resultados em nova janela
            Saida rf = new Saida(resultados);
            rf.setVisible(true);
        }
    }

    private List<Integer> lerArquivo(File arquivo) {
        List<Integer> numeros = new ArrayList<>();
        try (Scanner sc = new Scanner(arquivo)) {
            while (sc.hasNextInt()) {
                numeros.add(sc.nextInt());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao ler arquivo: " + e.getMessage());
        }
        return numeros;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblOrdenacao = new javax.swing.JLabel();
        btnCarregar = new javax.swing.JButton();
        lblMetodos = new javax.swing.JLabel();
        lblNumeros = new javax.swing.JLabel();
        lblSelecionados = new javax.swing.JLabel();
        chbBolha = new javax.swing.JCheckBox();
        chbSelecao = new javax.swing.JCheckBox();
        chbInsercao = new javax.swing.JCheckBox();
        chbAgitacao = new javax.swing.JCheckBox();
        chbPente = new javax.swing.JCheckBox();
        txtNumeros = new javax.swing.JTextField();
        btnExecutar = new javax.swing.JButton();
        txtSelecionados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOrdenacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrdenacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrdenacao.setText("Ordenação");

        btnCarregar.setText("Carregar Arquivo");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        lblMetodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetodos.setText("Métodos:");

        lblNumeros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeros.setText("Total n° carregados:");

        lblSelecionados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSelecionados.setText("Métodos selecionados:");

        chbBolha.setText("Bolha");

        chbSelecao.setText("Seleção");

        chbInsercao.setText("Inserção");
        chbInsercao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbInsercaoActionPerformed(evt);
            }
        });

        chbAgitacao.setText("Agitação");

        chbPente.setText("Pente");

        txtNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosActionPerformed(evt);
            }
        });

        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        txtSelecionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelecionadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(lblOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(chbInsercao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chbAgitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbBolha, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbPente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnExecutar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSelecionados, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSelecionados)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCarregar)
                                    .addGap(255, 255, 255))))
                        .addGap(0, 35, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCarregar, lblMetodos, lblNumeros, lblSelecionados});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chbAgitacao, chbBolha, chbInsercao, chbSelecao});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCarregar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbBolha)
                            .addComponent(chbSelecao)
                            .addComponent(chbPente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbAgitacao)
                            .addComponent(chbInsercao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblMetodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeros)
                    .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelecionados)
                    .addComponent(txtSelecionados, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExecutar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbInsercaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbInsercaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbInsercaoActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        txtSelecionados.setText(chamarSelecionados());

    if (numerosCarregados == null || numerosCarregados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum arquivo foi carregado!");
        return;
    }

    List<Resultado> resultados = new ArrayList<>();

    if (chbBolha.isSelected()) {
    resultados.add(Metodos.bolha(new ArrayList<>(numerosCarregados)));
    }
    if (chbSelecao.isSelected()) {
        resultados.add(Metodos.selecao(new ArrayList<>(numerosCarregados)));
    }
    if (chbInsercao.isSelected()) {
        resultados.add(Metodos.insercao(new ArrayList<>(numerosCarregados)));
    }
    if (chbAgitacao.isSelected()) {
        resultados.add(Metodos.agitacao(new ArrayList<>(numerosCarregados)));
    }
    if (chbPente.isSelected()) {
        resultados.add(Metodos.pente(new ArrayList<>(numerosCarregados)));
    }

    if (resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecione ao menos um método de ordenação!");
        return;
    }

    // Abre a janela de saída com os resultados
    Saida saida = new Saida(resultados);
    saida.setLocationRelativeTo(this); // centraliza
    saida.setVisible(true);
        
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        int arquivo = jFileChooser1.showOpenDialog(this);

        if (arquivo == JFileChooser.APPROVE_OPTION) {
            java.io.File arquivoSelecionado = jFileChooser1.getSelectedFile();
            numerosCarregados = lerArquivo(arquivoSelecionado);

        txtNumeros.setText(String.valueOf(numerosCarregados.size()));
        System.out.println("Arquivo carregado com " + numerosCarregados.size() + " números");
        }
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void txtNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosActionPerformed

    private void txtSelecionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelecionadosActionPerformed
        
    }//GEN-LAST:event_txtSelecionadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JCheckBox chbAgitacao;
    private javax.swing.JCheckBox chbBolha;
    private javax.swing.JCheckBox chbInsercao;
    private javax.swing.JCheckBox chbPente;
    private javax.swing.JCheckBox chbSelecao;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lblMetodos;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblOrdenacao;
    private javax.swing.JLabel lblSelecionados;
    private javax.swing.JTextField txtNumeros;
    private javax.swing.JTextField txtSelecionados;
    // End of variables declaration//GEN-END:variables
}
